name: MineQuest-Idle
main: com.theminequest.idle.Main
version: 2.0.0
description: Provides a map interface to MineQuest
author: Xu_R
website: www.theminequest.com

load: POSTWORLD

softdepend: [MineQuest]